
import type { PointOfInterest, Event, HighLevelCategory } from './types';
import { Landmark, Waves, GalleryVertical, Utensils, Castle, Trees, Home, NotebookPen, Headphones, User, Compass, Mountain, Ship, Building, Droplets, Church, ShoppingCart, Fish, Drama, Sparkles, Route } from 'lucide-react';

export const categories = {
  Temple: { icon: Landmark, color: 'text-rose-500' },
  Beach: { icon: Waves, color: 'text-cyan-500' },
  Museum: { icon: GalleryVertical, color: 'text-amber-600' },
  Food: { icon: Utensils, color: 'text-orange-500' },
  Heritage: { icon: Castle, color: 'text-stone-500' },
  Park: { icon: Trees, color: 'text-green-500' },
  Nature: { icon: Mountain, color: 'text-emerald-500' },
  Leisure: { icon: Building, color: 'text-indigo-500' },
  Excursion: { icon: Droplets, color: 'text-blue-500' },
  Church: { icon: Church, color: 'text-violet-500' },
  Shopping: { icon: ShoppingCart, color: 'text-pink-500' },
  Aquarium: { icon: Fish, color: 'text-blue-600' },
  Wildlife: { icon: Drama, color: 'text-teal-500' }
};

export const highLevelCategories: HighLevelCategory[] = [
  { 
    name: 'All', 
    icon: Sparkles, 
    subCategories: [] // Special case for 'All'
  },
  { 
    name: 'Spiritual & Heritage', 
    icon: Landmark, 
    subCategories: ['Temple', 'Heritage', 'Church'] 
  },
  { 
    name: 'Nature & Outdoors', 
    icon: Trees, 
    subCategories: ['Beach', 'Park', 'Nature', 'Wildlife'] 
  },
  { 
    name: 'Culture & Leisure', 
    icon: Drama, 
    subCategories: ['Museum', 'Leisure', 'Shopping', 'Aquarium', 'Food'] 
  },
  { 
    name: 'Adventure & Excursions', 
    icon: Route, 
    subCategories: ['Excursion'] 
  },
];


export const pointsOfInterest: PointOfInterest[] = [
  {
    id: 'kailasagiri',
    name: 'Kailasagiri',
    category: 'Park',
    description: 'A hilltop park with panoramic city and ocean views.',
    longDescription: 'Kailasagiri is a prime attraction in Visakhapatnam, offering breathtaking views of the sea and the city. It features large statues of Shiva and Parvati, a ropeway, and beautiful floral clock. It\'s a perfect spot for picnics and evening strolls.',
    imageUrl: 'https://www.adotrip.com/public/images/areas/5ca3308e16f46-Kailasagiri%20Places%20to%20See.jpg',
    imageHint: 'hilltop park',
    location: 'Hill Top Rd, Kailasagiri',
    coordinates: { lat: 17.7476, lng: 83.3375 },
    hours: '10:00 AM - 8:00 PM',
    fee: '₹5 (Entry), ₹90 (Ropeway)',
  },
  {
    id: 'rk-beach',
    name: 'Ramakrishna Beach',
    category: 'Beach',
    description: 'A popular urban beach known for its submarine museum.',
    longDescription: 'Known as RK Beach, it is famous for the INS Kurusura Submarine Museum. The beach is ideal for evening walks, with several eateries and parks lining its shores. The war memorial, Victory at Sea, is also a prominent landmark here.',
    imageUrl: 'https://im.hunt.in/cg/visakhapatnam/City-Guide/sea.jpg',
    imageHint: 'urban beach',
    location: 'RK Beach Road',
    coordinates: { lat: 17.7107, lng: 83.3229 },
    hours: 'Open 24 hours',
    fee: 'Free',
  },
  {
    id: 'simhachalam-temple',
    name: 'Simhachalam Temple',
    category: 'Temple',
    description: 'An ancient Hindu temple dedicated to Lord Narasimha.',
    longDescription: 'The Sri Varaha Lakshmi Narasimha temple, Simhachalam, is a Hindu temple situated on the Simhachalam Hill Range. It is dedicated to Lord Vishnu, who is worshipped there as Varaha Narasimha. The temple\'s architecture is a stunning blend of Kalinga and Chola styles.',
    imageUrl: 'https://media.tripinvites.com/places/visakhapatnam/simhachalam-temple/the-simhachalam-temple-featured.jpg',
    imageHint: 'hindu temple',
    location: 'Simhachalam',
    coordinates: { lat: 17.7673, lng: 83.2494 },
    hours: '7-11:30AM, 12:30-4PM, 6-9PM',
    fee: 'Free (General Darshan)',
    etiquette: 'Dress modestly, covering shoulders and knees. Remove footwear before entering the temple premises.',
  },
  {
    id: 'submarine-museum',
    name: 'INS Kursura Submarine Museum',
    category: 'Museum',
    description: 'A real submarine converted into a museum on RK Beach.',
    longDescription: 'The INS Kursura was a Kalvari-class diesel-electric submarine of the Indian Navy, which served for 31 years. It is now preserved as a museum on the shores of Ramakrishna Beach, giving visitors a glimpse into the life and workings inside a submarine.',
    imageUrl: 'https://yometro.com/images/places/ins-kurusura-submarine-museum.jpg',
    imageHint: 'submarine museum',
    location: 'RK Beach Road',
    coordinates: { lat: 17.7126, lng: 83.3253 },
    hours: '2:00 PM - 8:30 PM (Closed on Mondays)',
    fee: '₹40 for Adults, ₹20 for Children',
  },
  {
    id: 'bavikonda-buddhist-complex',
    name: 'Bavikonda Buddhist Complex',
    category: 'Heritage',
    description: 'Ruins of an ancient Buddhist monastery on a hilltop.',
    longDescription: 'Dating back to the 3rd century BC, Bavikonda is an important Buddhist heritage site. The complex includes several stupas, viharas, and pottery remnants, offering insight into the ancient Buddhist culture that flourished in this region.',
    imageUrl: 'https://holyshrines.in/wp-content/uploads/2017-05/Bavikonda_stupas.JPG',
    imageHint: 'ancient ruins',
    location: 'Near Thimmapuram',
    coordinates: { lat: 17.8488, lng: 83.4321 },
    hours: '9:00 AM - 5:00 PM',
    fee: '₹10 per person',
  },
  {
    id: 'rushikonda-beach',
    name: 'Rushikonda Beach',
    category: 'Beach',
    description: 'Picturesque beach known for water sports.',
    longDescription: 'With its golden sands and clear waters, Rushikonda Beach is a hub for water sports like jet skiing, windsurfing, and speed boating. The surrounding green hills add to its scenic beauty.',
    imageUrl: 'https://assets.telegraphindia.com/abp/2023/Oct/1697188562_untitled-design-2023-10-13t144551-610.jpg',
    imageHint: 'water sports',
    location: 'Rushikonda',
    coordinates: { lat: 17.7828, lng: 83.3871 },
    hours: 'Open 24 hours',
    fee: 'Free',
  },
  {
    id: 'yarada-beach',
    name: 'Yarada Beach',
    category: 'Beach',
    description: 'A serene and pristine beach surrounded by hills.',
    longDescription: 'Located on the west coast of Bay of Bengal, Yarada Beach is a stunning, less-crowded beach flanked by hills on three sides. It offers a calm retreat and spectacular sunset views.',
    imageUrl: 'https://cimages1.touristlink.com/repository/2014/11/YAR/ADA/BEA/CHV/IEW/7ST/yarada-beach-_-_view.jpg',
    imageHint: 'serene beach',
    location: 'Yarada',
    coordinates: { lat: 17.6534, lng: 83.2755 },
    hours: 'Open 24 hours',
    fee: '₹30 entry fee',
  },
  {
    id: 'bheemili-beach',
    name: 'Bheemili Beach',
    category: 'Beach',
    description: 'Historic beach with remnants of Dutch and British settlements.',
    longDescription: 'Bheemunipatnam, or Bheemili, is one of the oldest municipalities in India. The beach is known for its old Dutch cemetery, a lighthouse, and a small fishing harbor. It\'s a peaceful escape from the city.',
    imageUrl: 'https://www.yovizag.com/wp-content/uploads/2017/07/Bheemili-Beach-Visakhapatnam3.jpg',
    imageHint: 'historic beach',
    location: 'Bheemunipatnam',
    coordinates: { lat: 17.892, lng: 83.452 },
    hours: 'Open 24 hours',
    fee: 'Free',
  },
  {
    id: 'tenneti-park',
    name: 'Tenneti Park',
    category: 'Park',
    description: 'A beautiful coastal park with stunning sea views.',
    longDescription: 'Tenneti Park is a popular urban park located on the beachfront. It has well-maintained lawns, play areas, and offers breathtaking views of the coastline, making it a favorite spot for locals and tourists.',
    imageUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/10/4b/78/9b/tenneti-park.jpg',
    imageHint: 'coastal park',
    location: 'Beach Road, Jodugullapalem',
    coordinates: { lat: 17.7282, lng: 83.3424 },
    hours: '6:00 AM - 9:00 PM',
    fee: 'Free',
  },
  {
    id: 'tu-142-aircraft-museum',
    name: 'TU 142 Aircraft Museum',
    category: 'Museum',
    description: 'A naval aircraft converted into a museum.',
    longDescription: 'The Tupolev TU 142M is a long-range maritime patrol aircraft of the Indian Navy that has been converted into a museum. It provides an opportunity to learn about the aircraft\'s capabilities and its role in naval operations.',
    imageUrl: 'https://i.ytimg.com/vi/wyFGCudd3_c/maxresdefault.jpg',
    imageHint: 'aircraft museum',
    location: 'RK Beach Road',
    coordinates: { lat: 17.712, lng: 83.3245 },
    hours: '2:00 PM - 8:30 PM (Closed on Mondays)',
    fee: '₹70 for Adults',
  },
  {
    id: 'araku-valley',
    name: 'Araku Valley',
    category: 'Nature',
    description: 'A scenic hill station known for its coffee plantations.',
    longDescription: 'A popular day trip from Vizag, Araku Valley is a picturesque hill station famous for its pleasant climate, lush green forests, coffee plantations, and waterfalls. The journey by train through tunnels and hills is an experience in itself.',
    imageUrl: 'https://indiano.travel/wp-content/uploads/2022/04/Beautiful-Landscape-view-of-Araku-Valley.jpg',
    imageHint: 'hill station',
    location: 'Araku Valley',
    coordinates: { lat: 18.3333, lng: 82.8667 },
    hours: 'Best visited during the day',
    fee: 'Varies by activity',
  },
  {
    id: 'borra-caves',
    name: 'Borra Caves',
    category: 'Nature',
    description: 'Stunning limestone caves with stalactite and stalagmite formations.',
    longDescription: 'The Borra Caves are one of the largest caves in the country, located in the Ananthagiri hills of the Araku Valley. They are known for their spectacular, million-year-old stalactite and stalagmite formations.',
    imageUrl: 'https://www.holidify.com/images/compressed/attractions/attr_2194.jpg',
    imageHint: 'limestone caves',
    location: 'Near Araku Valley',
    coordinates: { lat: 18.2798, lng: 83.0416 },
    hours: '10:00 AM - 5:00 PM',
    fee: '₹60 for Adults',
  },
   {
    id: 'dolphins-nose',
    name: 'Dolphin\'s Nose',
    category: 'Park',
    description: 'A large rock promontory with a lighthouse.',
    longDescription: 'This large rock, 174 meters high, resembles a dolphin\'s nose. It offers a stunning view of the city and the harbor. The lighthouse on top of the hill is also a major attraction.',
    imageUrl: 'https://source.unsplash.com/600x400/?rock,viewpoint,lighthouse',
    imageHint: 'rock viewpoint',
    location: 'Yarada',
    coordinates: { lat: 17.6748, lng: 83.2847 },
    hours: '3:00 PM - 5:00 PM (Lighthouse)',
    fee: '₹10 for Lighthouse',
  },
  {
    id: 'kambalakonda-sanctuary',
    name: 'Kambalakonda Wildlife Sanctuary',
    category: 'Wildlife',
    description: 'A forest reserve with diverse flora and fauna.',
    longDescription: 'Kambalakonda is a dry evergreen forest with a variety of wildlife. It offers trekking trails, bird watching opportunities, and an ecotourism park, making it a great destination for nature lovers.',
    imageUrl: 'https://th-i.thgim.com/public/incoming/2ayjy0/article66488800.ece/alternates/LANDSCAPE_1200/Kambal02.jpg',
    imageHint: 'wildlife sanctuary',
    location: 'Near Indira Gandhi Zoological Park',
    coordinates: { lat: 17.7719, lng: 83.3331 },
    hours: '9:00 AM - 4:30 PM',
    fee: '₹20 per person',
  },
  {
    id: 'thotlakonda-buddhist-complex',
    name: 'Thotlakonda Buddhist Complex',
    category: 'Heritage',
    description: 'An ancient Buddhist settlement on a hilltop overlooking the sea.',
    longDescription: 'Thotlakonda provides a serene and spiritual experience with its ancient stupas, viharas, and a Mahastupa. The location on a hill offers panoramic views of the sea, making it a place of historical significance and natural beauty.',
    imageUrl: 'https://telugu.samayam.com/thumb/msid-71738981,width-1200,height-630,resizemode-4/year-ender-movie-awards-2019.jpg',
    imageHint: 'buddhist ruins',
    location: 'Near Bheemili',
    coordinates: { lat: 17.8631, lng: 83.4398 },
    hours: '9:00 AM - 5:00 PM',
    fee: '₹10 per person',
  },
  {
    id: 'lawsons-bay-beach',
    name: 'Lawson\'s Bay Beach',
    category: 'Beach',
    description: 'A calm and serene beach, considered an extension of RK Beach.',
    longDescription: 'Lawson\'s Bay Beach is a picturesque and tranquil stretch of coastline, perfect for swimming and sunbathing. Its calm waters and gentle waves make it a safer alternative to the main RK Beach, ideal for families.',
    imageUrl: 'https://www.hotelbeachside.com/top-10-most-beautiful-beaches-in-andhrapradesh/images/lawsonsbaybeach1.jpg',
    imageHint: 'calm beach',
    location: 'Beside RK Beach, towards Kailasagiri',
    coordinates: { lat: 17.724, lng: 83.3396 },
    hours: 'Open 24 hours',
    fee: 'Free',
  },
  {
    id: 'mangamaripeta-beach',
    name: 'Mangamaripeta Beach',
    category: 'Beach',
    description: 'Known for the Thotlakonda Buddhist Complex nearby and a natural rock arch.',
    longDescription: 'This beach is famous for its natural stone archway, which is a major draw for photographers. It is located close to the Thotlakonda Buddhist ruins, offering a mix of natural beauty and historical exploration.',
    imageUrl: 'https://d3sftlgbtusmnv.cloudfront.net/blog/wp-content/uploads/2024/09/Mangamaripeta-Beach-1.jpg',
    imageHint: 'rock arch',
    location: 'Near Thotlakonda, Bheemili Road',
    coordinates: { lat: 17.8542, lng: 83.4419 },
    hours: 'Open 24 hours',
    fee: 'Free',
  },
  {
    id: 'iskcon-temple',
    name: 'ISKCON Temple, Sagar Nagar',
    category: 'Temple',
    description: 'A beautiful and serene temple dedicated to Lord Krishna.',
    longDescription: 'The ISKCON temple in Sagar Nagar is a peaceful spiritual center. With its beautiful architecture and serene atmosphere, it\'s a perfect place for meditation and attending evening aartis.',
    imageUrl: 'https://templeyatri.in/wp-content/uploads/2024/07/iskcon_vizag-1.jpg',
    imageHint: 'krishna temple',
    location: 'Sagar Nagar',
    coordinates: { lat: 17.7681, lng: 83.3712 },
    hours: '4:30AM-1PM, 4PM-8:30PM',
    fee: 'Free',
    etiquette: 'Maintain silence and adhere to the temple dress code.',
  },
  {
    id: 'sri-kanaka-mahalakshmi-temple',
    name: 'Sri Kanaka Mahalakshmi Temple',
    category: 'Temple',
    description: 'A popular temple where devotees believe the goddess grants wishes.',
    longDescription: 'Located in Burujupeta, this temple is dedicated to the goddess of wealth, Sri Kanaka Mahalakshmi. It is one of the most revered and visited temples in Visakhapatnam.',
    imageUrl: 'https://www.pngkit.com/png/detail/360-3607047_sri-kanaka-mahalakshmi-ammavasi-temple.png',
    imageHint: 'goddess temple',
    location: 'Burujupeta, Old Town',
    coordinates: { lat: 17.6937, lng: 83.2936 },
    hours: '5:00 AM - 9:00 PM',
    fee: 'Free',
  },
  {
    id: 'sampath-vinayaka-temple',
    name: 'Sampath Vinayaka Temple',
    category: 'Temple',
    description: 'A famous Ganesha temple located in the heart of the city.',
    longDescription: 'This temple in Asilmetta is dedicated to Lord Ganesha and is a hub of spiritual activity. It is believed that seeking blessings here before starting any new venture brings success.',
    imageUrl: 'https://famoustemplesofindia.com/wp-content/uploads/2023/09/1-6.jpg',
    imageHint: 'ganesha temple',
    location: 'Asilmetta',
    coordinates: { lat: 17.7196, lng: 83.3159 },
    hours: '6:00 AM - 8:00 PM',
    fee: 'Free',
  },
  {
    id: 'ross-hill-church',
    name: 'Ross Hill Church',
    category: 'Church',
    description: 'A historic church on a hill, symbolizing religious harmony.',
    longDescription: 'Ross Hill Church, overlooking the port, is part of a unique trio of hills, each with a different religious shrine—a church, a mosque, and a temple, showcasing the city\'s religious harmony.',
    imageUrl: 'https://media.tripinvites.com/places/visakhapatnam/ross-hill-church/beautiful-statue-of-jesus-at-ross-church-featured.jpg',
    imageHint: 'hilltop church',
    location: 'Port Area',
    coordinates: { lat: 17.6881, lng: 83.2845 },
    hours: '9:00 AM - 6:00 PM',
    fee: 'Free',
  },
  {
    id: 'shirdi-sai-baba-temple',
    name: 'Shirdi Sai Baba Temple',
    category: 'Temple',
    description: 'A major temple dedicated to Sai Baba, known for its calm environment.',
    longDescription: 'Located in Seethammadhara, this temple is a peaceful sanctuary for devotees of Sai Baba. The temple complex is large and well-maintained, attracting crowds during festivals.',
    imageUrl: 'https://source.unsplash.com/600x400/?sai,baba,temple',
    imageHint: 'sai baba temple',
    location: 'Seethammadhara',
    coordinates: { lat: 17.7381, lng: 83.3134 },
    hours: '5:30 AM - 8:30 PM',
    fee: 'Free',
  },
  {
    id: 'vuda-park',
    name: 'VUDA Park (Taraka Rama Park)',
    category: 'Park',
    description: 'A popular recreational park with musical fountains and boating.',
    longDescription: 'VUDA Park, officially Taraka Rama Park, is a favorite among locals for its lush greenery, children\'s play areas, boating facilities, and spectacular musical fountain shows in the evening.',
    imageUrl: 'https://vizagtourism.org.in/images/places-to-visit/header/vuda-park-vizag-tourism-entry-fee-timings-holidays-reviews-header.jpg',
    imageHint: 'recreational park',
    location: 'Beach Road',
    coordinates: { lat: 17.7196, lng: 83.334 },
    hours: '9:00 AM - 8:30 PM',
    fee: '₹20 entry, other activities extra',
  },
  {
    id: 'matsyadarshini-aquarium',
    name: 'Matsyadarshini Aquarium',
    category: 'Aquarium',
    description: 'An aquarium showcasing a variety of freshwater and marine fish.',
    longDescription: 'Situated on the RK Beach, this aquarium is housed in a unique fish-shaped building. It features numerous tanks with a diverse collection of marine species, making it an educational visit for all ages.',
    imageUrl: 'https://img.traveltriangle.com/blog/wp-content/uploads/2024/07/Where-Is-Matsyadarshini-Aquarium.jpg',
    imageHint: 'fish aquarium',
    location: 'RK Beach Road',
    coordinates: { lat: 17.7118, lng: 83.3242 },
    hours: '9:00 AM - 7:00 PM',
    fee: '₹30 for Adults',
  },
  {
    id: 'visakha-museum',
    name: 'Visakha Museum',
    category: 'Museum',
    description: 'Museum showcasing the history of Visakhapatnam.',
    longDescription: 'Housed in a beautiful Dutch bungalow, the Visakha Museum displays historical treasures and artifacts of the Kalingandhra region, including armor, coins, and documents from the city\'s past.',
    imageUrl: 'https://vizagtourism.org.in/images/tourist-places/visakha-museum-vizag/visakha-museum-vizag-tourism-entry-ticket-price.jpg',
    imageHint: 'history museum',
    location: 'Beach Road',
    coordinates: { lat: 17.7126, lng: 83.3253 },
    hours: '11:00 AM - 7:00 PM (Closed on Fridays)',
    fee: '₹10 per person',
  },
  {
    id: 'tribal-museum-araku',
    name: 'Tribal Museum, Araku',
    category: 'Museum',
    description: 'Showcases the lifestyle and culture of local tribal communities.',
    longDescription: 'Located in Araku Valley, this museum offers a fascinating glimpse into the lives of the indigenous tribes of the Eastern Ghats. It features artifacts, tools, and traditional art.',
    imageUrl: 'https://i.pinimg.com/originals/bc/05/a6/bc05a672b13071226380f8b8f744cb5a.jpg',
    imageHint: 'tribal artifacts',
    location: 'Araku Valley',
    coordinates: { lat: 18.332, lng: 82.8717 },
    hours: '10:00 AM - 6:00 PM',
    fee: '₹40 for Adults',
  },
  {
    id: 'katiki-waterfalls',
    name: 'Katiki Waterfalls',
    category: 'Nature',
    description: 'A stunning waterfall near Borra Caves, requires a short trek.',
    longDescription: 'Originating from the Gosthani River, Katiki Waterfalls is a beautiful natural attraction near Borra Caves. Reaching the falls requires a bit of trekking, making it an adventurous outing.',
    imageUrl: 'https://yometro.com/images/places/katiki-falls.jpg',
    imageHint: 'jungle waterfall',
    location: 'Near Borra Caves, Araku',
    coordinates: { lat: 18.257, lng: 83.0531 },
    hours: '6:00 AM - 6:00 PM',
    fee: 'Free (Jeep ride extra)',
  },
  {
    id: 'lambasingi',
    name: 'Lambasingi',
    category: 'Nature',
    description: 'A small village known as the "Kashmir of Andhra Pradesh" for its cold temperatures.',
    longDescription: 'Lambasingi is famous for its chilly climate and misty landscapes, with temperatures sometimes dropping to zero degrees in winter. It\'s a perfect getaway for those seeking tranquility and natural beauty.',
    imageUrl: 'https://im.whatshot.in/img/2020/Jan/lamba3-1579255002.jpg',
    imageHint: 'misty hills',
    location: 'Near Chintapalli',
    coordinates: { lat: 17.848, lng: 82.355 },
    hours: 'Best visited early morning',
    fee: 'Free',
  },
  {
    id: 'cmr-central',
    name: 'CMR Central Mall',
    category: 'Shopping',
    description: 'A popular shopping mall with retail stores, a food court, and a cinema.',
    longDescription: 'CMR Central is one of the main shopping and entertainment hubs in Visakhapatnam, offering a wide range of national and international brands, a multi-cuisine food court, and a multiplex cinema.',
    imageUrl: 'https://source.unsplash.com/600x400/?shopping,mall,interior',
    imageHint: 'shopping mall',
    location: 'Maddilapalem',
    coordinates: { lat: 17.737, lng: 83.3175 },
    hours: '10:00 AM - 10:00 PM',
    fee: 'Free entry',
  },
  {
    id: 'fishing-harbor',
    name: 'Vizag Fishing Harbor',
    category: 'Leisure',
    description: 'A bustling harbor where you can see the daily life of fishermen.',
    longDescription: 'One of the largest fishing harbors in the country, this is a vibrant place to witness the local fishing industry in action. The morning fish auction is a particularly lively experience.',
    imageUrl: 'https://vizagfishingharbour.in/images/slide1.jpeg',
    imageHint: 'fishing boats',
    location: 'Port Area',
    coordinates: { lat: 17.684, lng: 83.28 },
    hours: 'Best visited early morning (5 AM - 8 AM)',
    fee: 'Free',
  },
  {
    id: 'kondakarla-ava',
    name: 'Kondakarla Ava',
    category: 'Excursion',
    description: 'A large freshwater lake known for birdwatching and boating.',
    longDescription: 'This serene lake is a haven for birdwatchers, especially during the migratory season. Visitors can enjoy boating on traditional palm-wood canoes and soak in the peaceful atmosphere.',
    imageUrl: 'https://www.yovizag.com/wp-content/uploads/2021/09/kondakarla-ava_WEB.jpg',
    imageHint: 'freshwater lake',
    location: 'Near Anakapalle',
    coordinates: { lat: 17.5878, lng: 82.9904 },
    hours: 'Best visited during the day',
    fee: 'Boating charges apply',
  }
];

export const events: Event[] = [
  {
    id: 'visakha-utsav',
    name: 'Visakha Utsav',
    date: 'December',
    description: 'A vibrant annual festival showcasing the culture, arts, and crafts of the Visakhapatnam district. It features cultural performances, food stalls, and exhibitions.',
    imageUrl: 'https://www.theindiatourism.com/images/india-fair-festival.jpg',
    imageHint: 'cultural festival',
  },
  {
    id: 'ratha-yatra',
    name: 'Ratha Yatra',
    date: 'June/July',
    description: 'The annual chariot festival dedicated to Lord Jagannath, celebrated with great fervor. A grand procession carries the deities on a decorated chariot through the city streets.',
    imageUrl: 'https://imgeng.jagran.com/images/2024/07/07/article/image/jagannath-rath-yatra-puri-2024-1720330682908.webp',
    imageHint: 'chariot procession',
  },
  {
    id: 'lumbini-festival',
    name: 'Lumbini Festival',
    date: 'December',
    description: 'A Buddhist festival celebrating the heritage of the region. It is held at the Nagarjunasagar dam and includes prayers, cultural events, and sermons by monks.',
    imageUrl: 'https://im.hunt.in/cg/visakhapatnam/City-Guide/LumbiniFestivalExhibition.jpg',
    imageHint: 'buddhist festival',
  },
];

export const navItems = [
  { href: '/', label: 'Home', icon: Home },
  { href: '/explore', label: 'Explore', icon: Compass },
  { href: '/planner', label: 'Planner', icon: NotebookPen },
  { href: '/audio', label: 'Audio', icon: Headphones },
  { href: '/profile', label: 'Profile', icon: User },
];
